name: mobile_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  asn1lib: ^1.6.5  
  pointycastle: ^3.9.1
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_windows: ^4.0.0
  flutter_secure_storage_platform_interface: ^2.0.1

flutter:
  uses-material-design: true